settings:
  world: "spawn" #Мир, в котором будет работать плагин
  y: 20 #Высота, при которой будет выполнена команда
  command: "rtp safe %player%" #Сама команда
messages:
  no-perms: "&c&lОШИБКА &8 &fУ Вас нет прав." #Сообщение при отсутствии права fmvoid.admin
  success-reload: "&c&lПЛАГИН &8 &fВы успешно перезагрузили плагин!" #Сообщение при успешном перезапуске плагина
  usage: "&c&lОШИБКА &8 &fПравильное использование: &c/fmv reload&f." #Сообщение при неправильном написании команды.